package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"aoc/util"
)

func TestDay8Sample(t *testing.T) {
	err := Day8(strings.NewReader(`
..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
..........`))
	require.NoError(t, err)

	err = Day8(strings.NewReader(`
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`))
	require.NoError(t, err)
}

func TestDay8(t *testing.T) {
	f, err := os.Open(filepath.Join(util.Cwd(), "day8.txt"))
	require.NoError(t, err)
	defer f.Close()
	err = Day8(f)
	require.NoError(t, err)
}
